#!/bin/sh

# 1st parameter is absolute path to component source directory
# 2nd parameter is absolute path to component build directory
# 3rd parameter is path to Python QA directory

# Note: calling master run_tests.sh in gnuradio core is not strictly
# correct, as it will result in a partially bogus PYTHONPATH, but it
# does make the correct paths in the second half so all is well.

../../../../../run_tests.sh \
    /home/next/gnuradio-3.2.2/gnuradio-core \
    /home/next/gnuradio-3.2.2/gnuradio-core \
    .
